<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vaibhav" failures="5" tests="24" name="dsAlgoTests.QueueTest" time="159.026" errors="0" timestamp="2025-02-06T09:11:37 IST" skipped="0">
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.608"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray" time="5.600">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray(QueueTest.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="8.687"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="8.913"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.375"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationUsingCollectionsDeque" time="4.400"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque" time="7.256">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque(QueueTest.java:142)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionOfImplementationOfQueueInPython" time="4.469">
    <failure message="No list of practice question found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No list of practice question found
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.listOfPracticeQuestionOfImplementationOfQueueInPython(QueueTest.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- listOfPracticeQuestionOfImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToImplementationUsingArrayTryEditor" time="9.216"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython" time="9.098">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython(QueueTest.java:135)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToQueueOperations" time="4.470"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToImplementationUsingArray" time="4.375"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="9.177"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationUsingCollectionsDequeTryEditor" time="7.125"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations" time="8.463">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations(QueueTest.java:156)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToPracticeQuestionOfImplementationOfQueueInPython" time="5.069"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationOfQueueInPython" time="4.078"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToQueueOperationsTryEditor" time="6.818"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationOfQueueInPythonTryEditor" time="9.868"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToPracticeQuestionImplementationUsingCollectionsDeque" time="4.767"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="5.035"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionImplementationUsingCollectionsDeque" time="4.498"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.819"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.842"/>
  <system-out/>
</testsuite> <!-- dsAlgoTests.QueueTest -->
