<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sukeerthsahana" failures="10" tests="58" name="dsAlgoTests.QueueTest" time="355.107" errors="0" timestamp="2025-02-18T00:22:13 CST" skipped="10">
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationOfQueueInPython" time="4.982"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationOfQueueInPython" time="6.284"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationOfQueueInPythonTryEditor" time="6.912"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationOfQueueInPythonTryEditor" time="5.723"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationUsingCollectionsDeque" time="4.188"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationUsingCollectionsDeque" time="5.560"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationUsingCollectionsDequeTryEditor" time="5.738"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationUsingCollectionsDequeTryEditor" time="6.968"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToImplementationUsingArray" time="4.525"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToImplementationUsingArray" time="6.410"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToImplementationUsingArrayTryEditor" time="6.921"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToImplementationUsingArrayTryEditor" time="5.198"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToQueueOperations" time="6.267"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToQueueOperations" time="4.755"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToQueueOperationsTryEditor" time="5.671"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToQueueOperationsTryEditor" time="6.686"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToPracticeQuestionOfImplementationOfQueueInPython" time="5.290"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToPracticeQuestionOfImplementationOfQueueInPython" time="6.400"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionOfImplementationOfQueueInPython" time="4.713">
    <failure message="No list of practice question found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No list of practice question found
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.listOfPracticeQuestionOfImplementationOfQueueInPython(QueueTest.java:207)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- listOfPracticeQuestionOfImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionOfImplementationOfQueueInPython" time="6.611">
    <skipped/>
  </testcase> <!-- listOfPracticeQuestionOfImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionOfImplementationOfQueueInPython" time="5.741">
    <failure message="No list of practice question found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No list of practice question found
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.listOfPracticeQuestionOfImplementationOfQueueInPython(QueueTest.java:207)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- listOfPracticeQuestionOfImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionOfImplementationOfQueueInPython" time="5.170">
    <skipped/>
  </testcase> <!-- listOfPracticeQuestionOfImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToPracticeQuestionImplementationUsingCollectionsDeque" time="5.625"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToPracticeQuestionImplementationUsingCollectionsDeque" time="5.007"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionImplementationUsingCollectionsDeque" time="5.767"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionImplementationUsingCollectionsDeque" time="4.604"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython" time="5.043">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython(QueueTest.java:258)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython" time="6.627">
    <skipped/>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython" time="5.651">
    <skipped/>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython" time="6.919">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython(QueueTest.java:258)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque" time="5.068">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque(QueueTest.java:278)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque" time="5.228">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque" time="8.031">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque(QueueTest.java:278)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque" time="7.415">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray" time="6.454">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray(QueueTest.java:297)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray" time="6.703">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray(QueueTest.java:297)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray" time="7.043">
    <skipped/>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray" time="5.167">
    <skipped/>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations" time="5.239">
    <skipped/>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations" time="7.146">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations(QueueTest.java:316)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations" time="5.452">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations(QueueTest.java:316)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations" time="6.598">
    <skipped/>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.537"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="8.588"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.209"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="8.215"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.109"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="5.968"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.210"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.339"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.620"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="8.367"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.345"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="5.787"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="5.564"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="5.950"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.174"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="6.625"/>
  <system-out/>
</testsuite> <!-- dsAlgoTests.QueueTest -->
