<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sukeerthsahana" failures="5" tests="20" name="dsAlgoTests.LinkedListTest" time="153.568" errors="0" timestamp="2025-02-05T12:28:42 CST" skipped="1">
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToDeletionTryEditor" time="6.738"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="18.117">
    <skipped/>
  </testcase> <!-- verifyCodeExecutionForLinkedList -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToCreateALinkedList" time="18.704"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkforPracticeQuestion" time="6.102">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkforPracticeQuestion(LinkedListTest.java:192)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkforPracticeQuestion -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkErrorMessageWhenExecutingWithoutCodeToInsertionTryEditor" time="9.026">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkErrorMessageWhenExecutingWithoutCodeToInsertionTryEditor(LinkedListTest.java:163)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeToInsertionTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkErrorMessageWhenExecutingWithoutCodeToTraversalTryEditor" time="7.948">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkErrorMessageWhenExecutingWithoutCodeToTraversalTryEditor(LinkedListTest.java:155)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeToTraversalTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToTypesOfLinkedList" time="5.665"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToTypesOfLinkedListTryEditor" time="10.288"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToIntroduction" time="8.553"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToInsertionTryEditor" time="5.962"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToTraversalTryEditor" time="6.240"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkErrorMessageWhenExecutingWithoutCodeToIntroductionTryEditor" time="6.222">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkErrorMessageWhenExecutingWithoutCodeToIntroductionTryEditor(LinkedListTest.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeToIntroductionTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToImplementLinkedListInPython" time="5.300"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToInsertion" time="5.458"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigatenavigateToIntroductionTryEditor" time="6.075"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToTraversal" time="5.154"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToCreateALinkedListTryEditor" time="6.327"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToImplementLinkedListInPythonTryEditor" time="6.726"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateDeletion" time="5.361"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkErrorMessageWhenExecutingWithoutCodeToDeletionTryEditor" time="3.602">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkErrorMessageWhenExecutingWithoutCodeToDeletionTryEditor(LinkedListTest.java:171)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeToDeletionTryEditor -->
  <system-out/>
</testsuite> <!-- dsAlgoTests.LinkedListTest -->
