<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SF0QLDR" failures="5" tests="33" name="dsAlgoTests.LinkedListTest" time="236.096" errors="0" timestamp="2025-02-04T10:37:29 EST" skipped="0">
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToInsertion" time="4.511"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToTypesOfLinkedList" time="7.763"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToCreateALinkedList" time="5.220"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="9.461"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToInsertionTryEditor" time="11.051"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToTraversalTryEditor" time="5.357"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="7.219"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToImplementLinkedListInPython" time="4.264"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="8.454"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="6.202"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToIntroduction" time="6.134"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="9.361"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="4.612"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToTypesOfLinkedListTryEditor" time="10.905"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToImplementLinkedListInPythonTryEditor" time="4.658"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateDeletion" time="8.184"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigatenavigateToIntroductionTryEditor" time="5.520"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkErrorMessageWhenExecutingWithoutCodeToDeletionTryEditor" time="10.055">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkErrorMessageWhenExecutingWithoutCodeToDeletionTryEditor(LinkedListTest.java:171)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeToDeletionTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="6.119"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToTraversal" time="4.923"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="5.722"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="8.125"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="7.510"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="5.114"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkErrorMessageWhenExecutingWithoutCodeToTraversalTryEditor" time="11.029">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkErrorMessageWhenExecutingWithoutCodeToTraversalTryEditor(LinkedListTest.java:155)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeToTraversalTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="9.000"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToDeletionTryEditor" time="8.747"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkforPracticeQuestion" time="7.548">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkforPracticeQuestion(LinkedListTest.java:192)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- checkforPracticeQuestion -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="4.951"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="navigateToCreateALinkedListTryEditor" time="4.755"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="verifyCodeExecutionForLinkedList" time="9.346"/>
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkErrorMessageWhenExecutingWithoutCodeToInsertionTryEditor" time="6.565">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkErrorMessageWhenExecutingWithoutCodeToInsertionTryEditor(LinkedListTest.java:163)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeToInsertionTryEditor -->
  <system-out/>
  <testcase classname="dsAlgoTests.LinkedListTest" name="checkErrorMessageWhenExecutingWithoutCodeToIntroductionTryEditor" time="7.711">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.LinkedListTest.checkErrorMessageWhenExecutingWithoutCodeToIntroductionTryEditor(LinkedListTest.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeToIntroductionTryEditor -->
  <system-out/>
</testsuite> <!-- dsAlgoTests.LinkedListTest -->
