<html>
<head>
<title>TestNG:  Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>26/6/0</td>
</tr><tr>
<td>Started on:</td><td>Wed Feb 05 18:19:28 EST 2025</td>
</tr>
<tr><td>Total time:</td><td>212 seconds (212522 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton()'><b>PracticeQuestionVaildAndInvalidDataWithSubmitButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Search the array, def search(input_list, num): 
    if num in input_list:
        print("Element Found")
    else:
        print("Element Not Found")

search([12, 23, 45, 67, 6, 90], 12), Submission Successful</td>
<td><div><pre>java.lang.AssertionError: Output mismatch for section: Arrays in Python expected [Submission Successful] but found [Some Tests failed. Please review code]
	at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:190)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace916188731", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace916188731'><pre>java.lang.AssertionError: Output mismatch for section: Arrays in Python expected [Submission Successful] but found [Some Tests failed. Please review code]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:629)
	at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:190)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton()'><b>PracticeQuestionVaildAndInvalidDataWithSubmitButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Squares of a Sorted Array, def sortedSquares(nums):
    squares_list = []
    for i in range(len(nums)):
        square = nums[i] * nums[i]
        squares_list.append(square)
    sorted_squares_list = sorted(squares_list)
    print(sorted_squares_list)
    return sorted_squares_list

sortedSquares([-7, -3, 2, 3, 11]), Submission Successful</td>
<td><div><pre>java.lang.IllegalArgumentException: Invalid Practice Question: Squares of a Sorted Array
	at dsAlgoPages.ArrayPage.PracticeQuestion(ArrayPage.java:187)
	at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:186)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 16 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace541022455", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace541022455'><pre>java.lang.IllegalArgumentException: Invalid Practice Question: Squares of a Sorted Array
	at dsAlgoPages.ArrayPage.PracticeQuestion(ArrayPage.java:187)
	at dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton(ArrayTest.java:186)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor()'><b>checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td><div><pre>java.lang.AssertionError: Test failed: Expected an error message when clicking the &apos;Run&apos; button without entering code, but no message was displayed.
	at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor(ArrayTest.java:144)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace48307881", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace48307881'><pre>java.lang.AssertionError: Test failed: Expected an error message when clicking the &apos;Run&apos; button without entering code, but no message was displayed.
	at org.testng.Assert.fail(Assert.java:99)
	at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeBasicOperationInListsForTryEditor(ArrayTest.java:144)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor()'><b>checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td><div><pre>java.lang.AssertionError: Test failed: Expected an error message when clicking the &apos;Run&apos; button without entering code, but no message was displayed.
	at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor(ArrayTest.java:154)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1667522824", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1667522824'><pre>java.lang.AssertionError: Test failed: Expected an error message when clicking the &apos;Run&apos; button without entering code, but no message was displayed.
	at org.testng.Assert.fail(Assert.java:99)
	at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeApplicationofArrayForTryEditor(ArrayTest.java:154)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor()'><b>checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td><div><pre>java.lang.AssertionError: Test failed: Expected an error message when clicking the &apos;Run&apos; button without entering code, but no message was displayed.
	at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor(ArrayTest.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1730324396", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1730324396'><pre>java.lang.AssertionError: Test failed: Expected an error message when clicking the &apos;Run&apos; button without entering code, but no message was displayed.
	at org.testng.Assert.fail(Assert.java:99)
	at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeArrayUsingListForTryEditor(ArrayTest.java:134)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>2</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor()'><b>checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td><div><pre>java.lang.AssertionError: Test failed: Expected an error message when clicking the &apos;Run&apos; button without entering code, but no message was displayed.
	at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor(ArrayTest.java:124)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace712682149", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace712682149'><pre>java.lang.AssertionError: Test failed: Expected an error message when clicking the &apos;Run&apos; button without entering code, but no message was displayed.
	at org.testng.Assert.fail(Assert.java:99)
	at dsAlgoTests.ArrayTest.checkErrorMessageWhenExecutingWithoutCodeInArrayInPythonForTryEditor(ArrayTest.java:124)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>3</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithRunButton()'><b>PracticeQuestionVaildAndInvalidDataWithRunButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Find Numbers with Even Number, def findNumbers(nums)
    c = 0
    for i in nums:
        j = str(i)
        x = len(j)
        if x % 2 == 0:
            c = c + 1
    print(float(c))
    return float(c)

findNumbers([12, 345, 2, 6, 7896])
, SyntaxError: bad input on line 1</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton()'><b>PracticeQuestionVaildAndInvalidDataWithSubmitButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Max Consecutive Ones, def findMaxConsecutiveOnes(nums):
    count = 0
    result = 0
    for num in nums:
        if num == 0:
            count = 0
        else:
            count += 1
            result = max(result, count)
    print(float(result))
    return float(result)

findMaxConsecutiveOnes([1, 0, 1, 1, 0, 1]), Submission Successful</td>
<td></td>
<td>2</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithRunButton()'><b>PracticeQuestionVaildAndInvalidDataWithRunButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Find Numbers with Even Number, def findNumbers(nums):
    c = 0
    for i in nums:
        j = str(i)
        x = len(j)
        if x % 2 == 0:
            c = c + 1
    print(float(c))
    return float(c)

findNumbers([12, 345, 2, 6, 7896]), 2.0</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithRunButton()'><b>PracticeQuestionVaildAndInvalidDataWithRunButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Squares of Sorted Array, def sortedSquares(nums):
    squares_list = []
    for i in range(len(nums)):
        square = nums[i] * nums[i]
        squares_list.append(square)
    sorted_squares_list = sorted(squares_list)
    print(sorted_squares_list)
    return sorted_squares_list

sortedSquares([-7, -3, 2, 3, 11]), [4, 9, 9, 49, 121]</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.navigateToArrayInPython()'><b>navigateToArrayInPython</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithRunButton()'><b>PracticeQuestionVaildAndInvalidDataWithRunButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Max Consecutive Ones, def findMaxConsecutiveOnes(nums)
    count = 0
    result = 0
    for num in nums:
        if num == 0:
            count = 0
        else:
            count += 1
            result = max(result, count)
    print(float(result))
    return float(result)

findMaxConsecutiveOnes([1, 0, 1, 1, 0, 1]), SyntaxError: bad input on line 1</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.verifyCodeExecutionForArraySections()'><b>verifyCodeExecutionForArraySections</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, invalid, NameError: name 'invalid' is not defined on line 1</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.navigateToArrayUsingListTryEditor()'><b>navigateToArrayUsingListTryEditor</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithRunButton()'><b>PracticeQuestionVaildAndInvalidDataWithRunButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Search the array, def search(input_list, num): 
    if num in input_list:
        print("Element Found")
    else:
        print("Element Not Found")

search([12, 23, 45, 67, 6, 90], 12), Element Found</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.verifyCodeExecutionForArraySections()'><b>verifyCodeExecutionForArraySections</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays Using List, print "hello", hello</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.navigateToApplicationOfArray()'><b>navigateToApplicationOfArray</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.verifyCodeExecutionForArraySections()'><b>verifyCodeExecutionForArraySections</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Basic Operations in Lists, invalid, NameError: name 'invalid' is not defined on line 1</td>
<td></td>
<td>4</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.verifyCodeExecutionForArraySections()'><b>verifyCodeExecutionForArraySections</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Applications of Array, invalid, NameError: name 'invalid' is not defined on line 1</td>
<td></td>
<td>5</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithRunButton()'><b>PracticeQuestionVaildAndInvalidDataWithRunButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Squares of Sorted Array, def sortedSquares(nums)
    squares_list = []
    for i in range(len(nums)):
        square = nums[i] * nums[i]
        squares_list.append(square)
    sorted_squares_list = sorted(squares_list)
    print(sorted_squares_list)
    return sorted_squares_list

sortedSquares([-7, -3, 2, 3, 11]), SyntaxError: bad input on line 1</td>
<td></td>
<td>2</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithRunButton()'><b>PracticeQuestionVaildAndInvalidDataWithRunButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Search the array, def search(input_list, num): 
    if num in input_list:
        print("Element Found")
    else
        print("Element Not Found")

search([12, 23, 45, 67, 6, 90], 12), SyntaxError: bad input on line 4</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.navigateToBasicOperationInList()'><b>navigateToBasicOperationInList</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.navigateToApplicationOfArrayTryEditor()'><b>navigateToApplicationOfArrayTryEditor</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td></td>
<td>5</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.navigateToArrayInPythonTryEditor()'><b>navigateToArrayInPythonTryEditor</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td></td>
<td>4</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.verifyCodeExecutionForArraySections()'><b>verifyCodeExecutionForArraySections</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Applications of Array, print "hello", hello</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.navigateToArrayUsingList()'><b>navigateToArrayUsingList</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.verifyCodeExecutionForArraySections()'><b>verifyCodeExecutionForArraySections</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays Using List, invalid, NameError: name 'invalid' is not defined on line 1</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.verifyCodeExecutionForArraySections()'><b>verifyCodeExecutionForArraySections</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Basic Operations in Lists, print "hello", hello</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.verifyCodeExecutionForArraySections()'><b>verifyCodeExecutionForArraySections</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, print "hello", hello</td>
<td></td>
<td>2</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithSubmitButton()'><b>PracticeQuestionVaildAndInvalidDataWithSubmitButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Find Numbers with Even Number, def findNumbers(nums):
    c = 0
    for i in nums:
        j = str(i)
        x = len(j)
        if x % 2 == 0:
            c = c + 1
    print(float(c))
    return float(c)

findNumbers([12, 345, 2, 6, 7896]), Submission Successful</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.PracticeQuestionVaildAndInvalidDataWithRunButton()'><b>PracticeQuestionVaildAndInvalidDataWithRunButton</b><br>Test class: dsAlgoTests.ArrayTest<br>Parameters: Arrays in Python, Max Consecutive Ones, def findMaxConsecutiveOnes(nums):
    count = 0
    result = 0
    for num in nums:
        if num == 0:
            count = 0
        else:
            count += 1
            result = max(result, count)
    print(float(result))
    return float(result)

findMaxConsecutiveOnes([1, 0, 1, 1, 0, 1]), 2.0</td>
<td></td>
<td>1</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
<tr>
<td title='dsAlgoTests.ArrayTest.navigateToBasicOperationInListTryEditor()'><b>navigateToBasicOperationInListTryEditor</b><br>Test class: dsAlgoTests.ArrayTest</td>
<td></td>
<td>0</td>
<td>dsAlgoTests.ArrayTest@602e0143</td></tr>
</table><p>
</body>
</html>